services:
  postgres:
    image: postgres:17.4
    container_name: fa-c002-midtest-postgres
    environment:
      POSTGRES_DB: midtest_db
      POSTGRES_USER: midtest_user
      POSTGRES_PASSWORD: midtest_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U midtest_user -d midtest_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
