version: 2

models:
  - name: dim_apps
    description: "App dimension table"
    columns:
      - name: app_key
        description: "Surrogate key for app dimension"
        data_tests:
          - unique
          - not_null
      - name: app_store_id
        data_tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Date dimension table"
    columns:
      - name: date_key
        description: "Surrogate key for date dimension"
        data_tests:
          - unique
          - not_null
      - name: date
        data_tests:
          - not_null

  - name: fct_app_daily_performance
    description: "Fact table for daily app performance metrics (star schema)"
    columns:
      - name: performance_key
        description: "Surrogate key for fact table"
        data_tests:
          - not_null
      - name: app_key
        description: "Foreign key to dim_apps"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_apps')
              field: app_key
      - name: date_key
        description: "Foreign key to dim_dates"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: ad_revenue
        data_tests:
          - not_null
      - name: installs
        data_tests:
          - not_null
